### ISSUE TITLE
clang++ on ubuntu

### ISSUE THREAD

**Issue by wolfcod** [fe-dagostino/lock-free#1]
I'm trying to build bm_arena_allocator (or any other benchmark) and I get this error on UBUNTU using clang++.
I tried also on a Windows Machine with Visual Studio 2022 latest update, but some std extensions are not yet supported by Microsoft.

`[main] Building folder: lock-free bm_arena_allocator
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /tmp/git/lock-free/build --config Debug --target bm_arena_allocator -j 3 --
[build] [ 50%] Built target nanobench
[build] Consolidate compiler generated dependencies of target bm_arena_allocator
[build] [ 75%] Building CXX object benchmarks/CMakeFiles/bm_arena_allocator.dir/bm_arena_allocator.cpp.o
[build] In file included from /tmp/git/lock-free/benchmarks/bm_arena_allocator.cpp:6:
[build] /tmp/git/lock-free/include/core/arena_allocator.h:466:21: error: variable of non-literal type 'std::lock_guard<mutex>' (aka 'std::lock_guard<core::mutex>') cannot be defined in a constexpr function
[build]     std::lock_guard mtx(_mtx_next);
[build]                     ^
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_mutex.h:223:11: note: 'lock_guard<core::mutex>' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move constructors
[build]     class lock_guard
[build]           ^
[build] In file included from /tmp/git/lock-free/benchmarks/bm_arena_allocator.cpp:6:
[build] /tmp/git/lock-free/include/core/arena_allocator.h:483:28: error: missing 'typename' prior to dependent type name 'core::memory_address<memory_slot, size_type>::base_t'
[build]     using addr_base_type = core::memory_address<memory_slot,size_type>::base_t;
[build]                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build]                            typename 
[build] /tmp/git/lock-free/include/core/arena_allocator.h:676:1: error: missing 'typename' prior to dependent type name 'arena_allocator<data_t, data_size_t, chunk_size, initial_size, size_limit, alloc_threshold, allocator_t>::lookup_table_type'
[build] arena_allocator<data_t,data_size_t,chunk_size,initial_size,size_limit,alloc_threshold,allocator_t>::lookup_table_type          
[build] ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] typename 
[build] /tmp/git/lock-free/include/core/arena_allocator.h:674:1: error: requires clause differs in template redeclaration
[build] template< typename data_t, typename data_size_t, data_size_t chunk_size, data_size_t initial_size, data_size_t size_limit,
[build] ^
[build] /tmp/git/lock-free/include/core/arena_allocator.h:67:10: note: previous template declaration is here
[build] requires std::is_unsigned_v<data_size_t> && (std::is_same_v<data_size_t,u_int32_t> || std::is_same_v<data_size_t,u_int64_t>)
[build]          ^
[build] In file included from /tmp/git/lock-free/benchmarks/bm_arena_allocator.cpp:7:
[build] /tmp/git/lock-free/include/arena_allocator.h:454:28: error: missing 'typename' prior to dependent type name 'core::memory_address<memory_slot, size_type>::base_t'
[build]     using addr_base_type = core::memory_address<memory_slot,size_type>::base_t;
[build]                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build]                            typename 
[build] /tmp/git/lock-free/include/arena_allocator.h:458:39: error: no matching constructor for initialization of 'const std::lock_guard<std::mutex>'
[build]     const std::lock_guard<std::mutex> lock(_mtx_mem_chunks);
[build]                                       ^    ~~~~~~~~~~~~~~~
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_mutex.h:228:16: note: candidate constructor not viable: 1st argument ('const lock_free::arena_allocator::mutex_type' (aka 'const std::mutex')) would lose const qualifier
[build]       explicit lock_guard(mutex_type& __m) : _M_device(__m)
[build]                ^
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_mutex.h:237:7: note: candidate constructor not viable: no known conversion from 'const lock_free::arena_allocator::mutex_type' (aka 'const std::mutex') to 'const std::lock_guard<std::mutex>' for 1st argument
[build]       lock_guard(const lock_guard&) = delete;
[build]       ^
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_mutex.h:231:7: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
[build]       lock_guard(mutex_type& __m, adopt_lock_t) noexcept : _M_device(__m)
[build]       ^
[build] In file included from /tmp/git/lock-free/benchmarks/bm_arena_allocator.cpp:7:
[build] /tmp/git/lock-free/include/arena_allocator.h:458:39: error: variable of non-literal type 'const std::lock_guard<std::mutex>' cannot be defined in a constexpr function
[build]     const std::lock_guard<std::mutex> lock(_mtx_mem_chunks);
[build]                                       ^
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_mutex.h:223:11: note: 'lock_guard<std::mutex>' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move constructors
[build]     class lock_guard
[build]           ^
[build] In file included from /tmp/git/lock-free/benchmarks/bm_arena_allocator.cpp:7:
[build] /tmp/git/lock-free/include/arena_allocator.h:483:28: error: missing 'typename' prior to dependent type name 'core::memory_address<memory_slot, size_type>::base_t'
[build]     using addr_base_type = core::memory_address<memory_slot,size_type>::base_t;
[build]                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build]                            typename 
[build] /tmp/git/lock-free/include/arena_allocator.h:678:1: error: missing 'typename' prior to dependent type name 'arena_allocator<data_t, data_size_t, chunk_size, initial_size, size_limit, alloc_threshold, allocator_t>::lookup_table_type'
[build] arena_allocator<data_t,data_size_t,chunk_size,initial_size,size_limit,alloc_threshold,allocator_t>::lookup_table_type          
[build] ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] typename 
[build] /tmp/git/lock-free/include/arena_allocator.h:676:1: error: requires clause differs in template redeclaration
[build] template< typename data_t, typename data_size_t, data_size_t chunk_size, data_size_t initial_size, data_size_t size_limit,
[build] ^
[build] /tmp/git/lock-free/include/arena_allocator.h:66:10: note: previous template declaration is here
[build] requires std::is_unsigned_v<data_size_t> && (std::is_same_v<data_size_t,u_int32_t> || std::is_same_v<data_size_t,u_int64_t>)
[build]          ^
[build] 10 errors generated.
[build] gmake[3]: *** [benchmarks/CMakeFiles/bm_arena_allocator.dir/build.make:76: benchmarks/CMakeFiles/bm_arena_allocator.dir/bm_arena_allocator.cpp.o] Error 1
[build] gmake[2]: *** [CMakeFiles/Makefile2:175: benchmarks/CMakeFiles/bm_arena_allocator.dir/all] Error 2
[build] gmake[1]: *** [CMakeFiles/Makefile2:182: benchmarks/CMakeFiles/bm_arena_allocator.dir/rule] Error 2
[build] gmake: *** [Makefile:150: bm_arena_allocator] Error 2
[build] Build finished with exit code 2
`

**Comment by fe-dagostino** [comment]
Thanks for checking with CLang.14, I had to clean up all cmake cache to get on the same page. 
I found that there are few missing part in CLang that are supposed to be updated. 
- create core::lock_guard  with constexpr in order to avoid using std::lock_guard and leverage costexpr inline instead. Clang implementation should be updated.
- explict add typename 
- explict repeat constraints (requires) for external static initialization in both arena_allocators.
- also replaced u_intXX_t with uintXX_t
Please try again, all should compile.
